### ISSUE TITLE
Error in CSI2_COMPLEXIO_IRQENABLE	definition

### ISSUE THREAD

**Issue by allsey87** [omapconf/omapconf#32]
https://github.com/omapconf/omapconf/blob/master/arch/arm/mach-omap/omap4/prcm/camera44xx.h#L60

It seems like this one register randomly points to CSI2_COMPLEXIO_IRQENABLE for CSI B, while the rest point to CSI A...

**Comment by nmenon** [comment]
care to post a patch for the same?

**Comment by nmenon** [comment]
Ping?

**Comment by allsey87** [comment]
Sorry, no time at the moment, I'm working on a patch for the ISS...

**Comment by nmenon** [comment]
ok. just let HAL know that he can send a patch as well..

**Comment by allsey87** [comment]
HAL... Hardware Abstraction Layer?

**Comment by nmenon** [comment]
I was just kidding....

**Comment by nmenon** [comment]
Closing this
