### ISSUE TITLE
/dev/mem doesn't exist under linux 4.0.5 stable

### ISSUE THREAD

**Issue by allsey87** [omapconf/omapconf#33]
Perhaps consider editing below messages to indicate what needs to be built in the kernel to get /dev/mem back, when it isn't present. Error about privileged access being required is confusing when running as root.

root@target:~# ./omapconf read 0x4A100068
lmem_map(): could not open "/dev/mem"!
OMAPCONF (rev 1.68 built Wed Oct 16 04:13:08 IST 2013)

'/dev/mem' could not be opened.
Privileged access required to run omapconf.

**Comment by nmenon** [comment]
Could you make a proposal as to what we could have here?

**Comment by allsey87** [comment]
This will take some time to look into properly, however from the reading I
did do in the 20 minutes that I had, I think there might be a way to
perform the same low level access via debugfs...

**Comment by nmenon** [comment]
ok. closing this issue until a proper patch is provided. NOTE: we should ensure we maintain compliance that this tool is:
a) not dependent on specific kernel features other than the bare minimum (like memory access etc).
b) can run on other posix compliant OSes providing similar interfaces.
