### ISSUE TITLE
gcc 5.2.1: ubuntu wily (15.10) 

### ISSUE THREAD

**Issue by RobertCNelson** [omapconf/omapconf#34]
Just a few build errors with gcc 5.2.1

http://rcn-ee.homeip.net:81/farm/testing/tiomapconf_1.72.0-git20150825-1~bpo1510+20150826+1_armhf.build

Regards,

**Comment by nmenon** [comment]
This should be fixed now. please confirm in the next build - patches pushed to master. (and I have gcc 5.1 now.. :P )

**Comment by RobertCNelson** [comment]
gcc 5.2.1 is ubuntu wily 15.10 is picky!

http://rcn-ee.homeip.net:81/farm/testing/tiomapconf_1.72.0-git20150827-1~bpo1510+20150827+1_armhf.build

```
linux/linux_mem.c:239:34: warning: 'mem_map_base' is static but used in inline function 'lmem_phys2virt' which is not static
  return (void *) ((unsigned int) mem_map_base +

common/mem.o: In function `mem_phys2virt':
/Â«PKGBUILDDIRÂ»/common/mem.c:156: undefined reference to `lmem_phys2virt'
collect2: error: ld returned 1 exit status
Makefile:393: recipe for target 'omapconf' failed
```
Regards,

**Comment by nmenon** [comment]
Grrrr.... trying to get gcc 5.2 - probably any prebuilt might have helped..

**Comment by nmenon** [comment]
Robert - thanks for the access. the fixes have been pushed. lets re-open if we have further issues.
