### ISSUE TITLE
seeing "cpu not supported messages" on DRA7xx

### ISSUE THREAD

**Issue by brad-griffis** [omapconf/omapconf#39]
We get a lot of these messages:

omapconf: powerdm_deinit(): cpu not supported!!!
omapconf: clockdm_deinit(): cpu not supported!!!

For example:

root@dra7xx-evm:~# omapconf --cpuinfo
OMAPCONF (rev v1.73 built Mon Oct 24 09:39:52 IST 2016)

HW Platform:
Generic DRA74X (Flattened Device Tree)
DRA75X ES1.0 GP Device (STANDARD performance (1.0GHz))
DIE ID: 74780000-3FBA0702-0163DBA7-1400C010
TPS659038 ES1.0

omapconf: powerdm_deinit(): cpu not supported!!!
omapconf: clockdm_deinit(): cpu not supported!!!

This issue was originally reported here:

https://e2e.ti.com/support/arm/automotive_processors/f/1020/t/580618

**Comment by nmenon** [comment]
@brad-griffis "omapconf: powerdm_deinit(): cpu not supported!!!
omapconf: clockdm_deinit(): cpu not supported!!!"

we dont have clockdomain and power domain description in omapconf for dra7. this has been there based on the limited support of dra7 that was added.

**Comment by nmenon** [comment]
@brad-griffis  can you see if https://github.com/omapconf/omapconf/commit/1d2fa2b71fd446dae6d43a265ad75315f47a7f98 helps your case? if it works, I can merge it in with your tested-by tag.

**Comment by nmenon** [comment]
As per https://e2e.ti.com/support/arm/automotive_processors/f/1020/p/580618/2132716#2132716 it seems to help. will merge to master.
